### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by Xi-Mu-Yu** [CUHK-AIM-Group/DiffRect#2]
Hello, there seems to be an error with val.list and test.list in the MS-CMRSEG19 dataset. For example, test.list in mscmrseg19_split1 has only one file name. The test.list of mscmrseg19_split2 is the same as the val.list

**Comment by xinyuliu-jeffrey** [comment]
Hi @BeiZhiRen, thanks for your interest in our work!

Different from ACDC that have both val and test, in MS-CMRSEG19 dataset and Decathlon Prostate, we actually **only split the dataset into training and validation dataset**. The performance are reported as the average of performance on the validation sets of two different splits. The test list are not used for these two datasets.

Hope this helps!

**Comment by Xi-Mu-Yu** [comment]
> 您好，感谢您对我们的工作感兴趣！
> 
> 与 ACDC 同时具有 val 和 test 不同，在 MS-CMRSEG19 数据集和迪卡侬前列腺中，我们**实际上只将数据集拆分为训练数据集和验证数据集**。性能报告为两个不同拆分的验证集上的平均性能。测试列表不用于这两个数据集。
> 
> 希望这有帮助！
Ok, I see, thanks for your answers and contributions in semi-supervised semantic segmentation, I will do my best to quote and promote your article

**Comment by xinyuliu-jeffrey** [comment]
@BeiZhiRen Thanks again for bring this to our attention!
